name: Auto-update
on:
  repository_dispatch:
    types: [web-update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: main
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.80.0'
        extended: true
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        repository: ${{ github.event.client_payload.repository }}
        token: ${{ secrets.AUTOBUILD_REPO_PAT }}
        ref: ${{ github.event.client_payload.ref }}
        path: client
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python deps
      run: |
        (test -f client/requirements.txt && python -m pip install -r client/requirements.txt) || /bin/true
    - name: Build
      run: |
        cd client
        ${{ github.event.client_payload.build_command }}
    - name: Replace
      run: |
        rm -rf main/${{ github.event.client_payload.repository_name }}
        mv client/${{ github.event.client_payload.site_location }}/public main/${{ github.event.client_payload.repository_name }}
        cd main
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        test -z "$(git status --porcelain)" || (git add -A && git commit -m "Update pages" && git push)
